### ISSUE TITLE
I dont quite understand the windows set up

### ISSUE THREAD

**Issue by jaypitti** [CrossR/dotfiles#6]
im trying to get oni setup and I cant seem to get things going and i dont really understand the windows set up with allowing the "git folder" to handle the config with the link, any way you could elaborate?

**Comment by CrossR** [comment]
For my config, I've got the `oni` and `nvim` config folders linked from my Git folder, to the location they are supposed to live.

This lets Oni/nvim find the config in the place they expect, but also lets my config live in a single git folder, so the changes can be easily updated etc.

On Linux I'd just link the files, but Windows doesn't let you link a file over disks so since my git folder lives on my `F:` drive, I can't just link the files, which is why I use the folder.

If you don't want it in Git, or don't mind manually moving over occasionally, you can ignore it and just put the config in the correct place with no linking.

**Comment by jaypitti** [comment]
Thanks a lot for the prompt reply, that cleared it up for me and I was able to get it working!

**Comment by CrossR** [comment]
Glad you got it working!
